### ISSUE TITLE
Specify custom `dbSync` port

### ISSUE THREAD

**Issue by aciceri** [blockfrost/blockfrost-backend-ryo#88]
As written in the README, one can set `dbSync`' `host`, `user` and `database` but cannot set `port`.
For example if I put this in configuration I can connect to my postgres db on port 5432 (default one).
```yaml
// Cardano DB Sync SQL connection
dbSync: {
  host: 'postgres-preview',
  user: 'username',
  database: 'password',
}
```
it perfectly works, but if I try to manually specify the port in the `host` like this:
```yaml
// Cardano DB Sync SQL connection
dbSync: {
  host: 'postgres-preview:5432',
  user: 'username',
  database: 'password',
}
```
I get the following error:
```
2023-02-23T17:00:01: Error while connecting to DB Sync. Error: getaddrinfo ENOTFOUND postgres-preview:5432 at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,   
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'postgres-preview:5432'
}
```
Should a new `port` field be added?
